---
#
# Ansible managed
#
repository:
  description: Samba for RHEL/CentOS.
  homepage: https://buluma.github.io/
  topics: networking, system, samba, windows, filesystem, fileshare, sharing, files, ansible, molecule, tox, playbook
